# frozen_string_literal: true

require('starkcore')
require_relative('split_profile')
require_relative('../utils/rest')

module StarkBank
  class SplitProfile
    # # SplitProfile::Log object
    #
    # Every time a SplitProfile entity is modified, a corresponding SplitProfile::Log
    # is generated for the entity. This log is never generated by the
    # user, but it can be retrieved to check additional information
    # on the SplitProfile.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - profile [SplitProfile]: SplitProfile entity to which the log refers to.
    # - errors [list of strings]: list of errors linked to this SplitProfile event. The API does not currently return errors for SplitProfile events, so this is always nil.
    # - type [string]: type of the SplitProfile event which triggered the log creation. ex: 'success' or 'failed'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :type, :errors, :profile
      def initialize(id:, created:, type:, errors:, profile:)
        super(id)
        @type = type
        @errors = errors
        @profile = profile
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific SplitProfile::Log
      #
      # Receive a single SplitProfile::Log object previously created by the Stark Bank API by its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - SplitProfile::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve SplitProfile::Logs
      #
      # Receive a generator of SplitProfile::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by event types. ex: 'created' or 'updated'
      # - profile_ids [list of strings, default nil]: list of SplitProfile ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - generator of SplitProfile::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, profile_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          profile_ids: profile_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged SplitProfile::Logs
      #
      # Receive a list of up to 100 SplitProfile::Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your requests.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 50
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by event types. ex: 'created' or 'updated'
      # - profile_ids [list of strings, default nil]: list of SplitProfile ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - list of SplitProfile::Log objects with updated attributes
      # - cursor to retrieve the next page of SplitProfile::Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, profile_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          profile_ids: profile_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkBank::SplitProfile.resource[:resource_maker]
        {
          resource_name: 'SplitProfileLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              created: json['created'],
              type: json['type'],
              errors: json['errors'],
              profile: StarkCore::Utils::API.from_api_json(request_maker, json['profile'])
            )
          }
        }
      end
    end
  end
end
