# frozen_string_literal: true

require('starkcore')
require_relative('invoicepullsubscription')
require_relative('../utils/rest')

module StarkBank
  class InvoicePullSubscription
    # # InvoicePullSubscription::Log object
    #
    # Every time an InvoicePullSubscription entity is updated, a corresponding InvoicePullSubscription::Log is
    # generated for the entity. This Log is never generated by the user, but it can be retrieved to check
    # additional information on the InvoicePullSubscription.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - subscription [InvoicePullSubscription]: InvoicePullSubscription entity to which the log refers to.
    # - errors [list of strings]: list of errors linked to this InvoicePullSubscription event
    # - type [string]: type of the InvoicePullSubscription event which triggered the log creation. ex: 'pending' or 'success'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :subscription, :errors, :type, :created
      def initialize(id: nil, subscription: nil, errors: nil, type: nil, created: nil)
        super(id)
        @subscription = subscription
        @errors = errors
        @type = type
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific InvoicePullSubscription::Log
      #
      # Receive a single InvoicePullSubscription::Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - InvoicePullSubscription::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve InvoicePullSubscription::Logs
      #
      # Receive a generator of InvoicePullSubscription::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'paid', 'canceled', 'overdue']
      # - subscription_ids [list of strings, default nil]: list of InvoicePullSubscription ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - generator of InvoicePullSubscription::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, subscription_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          subscription_ids: subscription_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged InvoicePullSubscription::Logs
      #
      # Receive a list of up to 100 InvoicePullSubscription::Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your requests.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'paid', 'canceled', 'overdue']
      # - subscription_ids [list of strings, default nil]: list of InvoicePullSubscription ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - list of InvoicePullSubscription::Log objects with updated attributes and cursor to retrieve the next page of InvoicePullSubscription::Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, subscription_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          subscription_ids: subscription_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        subscription_maker = StarkBank::InvoicePullSubscription.resource[:resource_maker]
        {
          resource_name: 'InvoicePullSubscriptionLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              subscription: StarkCore::Utils::API.from_api_json(subscription_maker, json['subscription']),
              errors: json['errors'],
              type: json['type'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
