# frozen_string_literal: true

require_relative('../utils/resource')
require_relative('../utils/rest')
require_relative('../utils/checks')
require_relative('transfer')

module StarkBank
  class Transfer
    # # Transfer::Log object
    #
    # Every time a Transfer entity is modified, a corresponding Transfer::Log
    # is generated for the entity. This log is never generated by the
    # user.
    #
    # ## Attributes:
    # - id [string]: unique id returned when the log is created. ex: "5656565656565656"
    # - transfer [Transfer]: Transfer entity to which the log refers to.
    # - errors [list of strings]: list of errors linked to this BoletoPayment event.
    # - type [string]: type of the Transfer event which triggered the log creation. ex: "processing" or "success"
    # - created [DateTime]: creation datetime for the transfer. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkBank::Utils::Resource
      attr_reader :id, :created, :type, :errors, :transfer
      def initialize(id:, created:, type:, errors:, transfer:)
        super(id)
        @type = type
        @errors = errors
        @transfer = transfer
        @created = StarkBank::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific Log
      #
      # Receive a single Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: "5656565656565656"
      #
      # ## Parameters (optional):
      # - user [Project object]: Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - Log object with updated attributes
      def self.get(id:, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve Logs
      #
      # Receive a generator of Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - transfer_ids [list of strings, default nil]: list of Transfer ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
      # - types [list of strings, default nil]: filter retrieved objects by types. ex: "success" or "failed"
      # - after [Date, default nil] date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date, default nil] date filter for objects only before specified date. ex: Date.new(2020, 3, 10)
      # - user [Project object, default nil]: Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - list of Log objects with updated attributes
      def self.query(limit: nil, transfer_ids: nil, types: nil, after: nil, before: nil, user: nil)
        after = StarkBank::Utils::Checks.check_date(after)
        before = StarkBank::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_list(user: user, limit: limit, transfer_ids: transfer_ids, types: types, after: after, before: before, **resource)
      end

      def self.resource
        transfer_maker = StarkBank::Transfer.resource[:resource_maker]
        {
          resource_name: 'TransferLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              created: json['created'],
              type: json['type'],
              errors: json['errors'],
              transfer: StarkBank::Utils::API.from_api_json(transfer_maker, json['transfer'])
            )
          }
        }
      end
    end
  end
end
