# frozen_string_literal: true

require('starkcore')
require_relative('corporatepurchase')
require_relative('../utils/rest')

module StarkBank
  class CorporatePurchase
    # # CorporatePurchase::Log object
    #
    # Every time a CorporatePurchase entity is updated, a corresponding CorporatePurchase::Log is generated for the entity.
    # This Log is never generated by the user, but it can be retrieved to check additional information on the CorporatePurchase.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - purchase [CorporatePurchase]: CorporatePurchase entity to which the log refers to.
    # - description [string]: purchase descriptions. ex: 'my_description'
    # - corporate_transaction_id [string]: transaction ID related to the CorporateCard.
    # - errors [list of strings]: list of errors linked to this CorporatePurchase event
    # - type [string]: type of the CorporatePurchase event which triggered the log creation. ex: 'approved', 'canceled', 'confirmed', 'denied', 'reversed', 'voided'.
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :purchase, :description, :corporate_transaction_id, :errors, :type, :created
      def initialize(id: nil, purchase: nil, description: nil, corporate_transaction_id: nil, errors: nil, type: nil, created: nil)
        super(id)
        @purchase = purchase
        @description = description
        @corporate_transaction_id = corporate_transaction_id
        @errors = errors
        @type = type
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific CorporatePurchase::Log
      #
      # Receive a single CorporatePurchase::Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - CorporatePurchase::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve CorporatePurchase::Logs
      #
      # Receive a generator of CorporatePurchase::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['approved', 'canceled', 'confirmed', 'denied', 'reversed', 'voided']
      # - purchase_ids [list of strings, default nil]: list of Purchase ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: list of CorporatePurchase ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - generator of CorporatePurchase::Log objects with updated attributes
      def self.query(ids: nil, limit: nil, after: nil, before: nil, types: nil, purchase_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          purchase_ids: purchase_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged CorporatePurchase::Logs
      #
      # Receive a list of up to 100 Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your purchases.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['approved', 'canceled', 'confirmed', 'denied', 'reversed', 'voided']
      # - purchase_ids [list of strings, default nil]: list of Purchase ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: list of CorporatePurchase ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - list of CorporatePurchase::Log objects with updated attributes
      # - cursor to retrieve the next page of Log objects
      def self.page(cursor: nil, ids: nil, limit: nil, after: nil, before: nil, types: nil, purchase_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          purchase_ids: purchase_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkBank::CorporatePurchase.resource[:resource_maker]
        {
          resource_name: 'CorporatePurchaseLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              purchase: StarkCore::Utils::API.from_api_json(request_maker, json['purchase']),
              description: json['description'],
              corporate_transaction_id: json['corporate_transaction_id'],
              errors: json['errors'],
              type: json['type'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
