# frozen_string_literal: true

require('starkcore')
require_relative('merchant_card')
require_relative('../utils/rest')

module StarkBank
  class MerchantCard
    # # MerchantCard::Log object
    #
    # Every time a MerchantCard entity is updated, a corresponding MerchantCard::Log is generated for the entity. This
    # log is never generated by the user.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - card [MerchantCard]: MerchantCard entity to which the log refers to.
    # - errors [list of strings]: list of errors linked to this MerchantCard event
    # - type [string]: type of the MerchantCard event which triggered the log creation. ex: 'created', 'updated'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    # - updated [DateTime]: latest update datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :updated, :type, :errors, :card
      def initialize(id:, created:, updated:, type:, errors:, card:)
        super(id)
        @type = type
        @errors = errors
        @card = card
        @created = StarkCore::Utils::Checks.check_datetime(created)
        @updated = StarkCore::Utils::Checks.check_datetime(updated)
      end

      # # Retrieve a specific MerchantCard::Log
      #
      # Receive a single MerchantCard::Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - MerchantCard::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve MerchantCard::Logs
      #
      # Receive a generator of MerchantCard::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - card_ids [list of strings, default nil]: list of MerchantCard ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by event types. ex: ['created', 'updated']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - generator of MerchantCard::Log objects with updated attributes
      def self.query(limit: nil, card_ids: nil, after: nil, before: nil, types: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          limit: limit,
          card_ids: card_ids,
          after: after,
          before: before,
          types: types,
          user: user,
          **resource
        )
      end

      # # Retrieve paged MerchantCard::Logs
      #
      # Receive a list of up to 100 MerchantCard::Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your logs.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - card_ids [list of strings, default nil]: list of MerchantCard ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by event types. ex: ['created', 'updated']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - list of MerchantCard::Log objects with updated attributes
      # - cursor to retrieve the next page of MerchantCard::Log objects
      def self.page(cursor: nil, limit: nil, card_ids: nil, after: nil, before: nil, types: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          card_ids: card_ids,
          after: after,
          before: before,
          types: types,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkBank::MerchantCard.resource[:resource_maker]
        {
          resource_name: 'MerchantCardLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              created: json['created'],
              updated: json['updated'],
              type: json['type'],
              errors: json['errors'],
              card: StarkCore::Utils::API.from_api_json(request_maker, json['card'])
            )
          }
        }
      end
    end
  end
end
