# frozen_string_literal: true

require('starkcore')
require_relative('corporatecard')
require_relative('../utils/rest')

module StarkBank
  class CorporateCard
    # # CorporateCard::Log object
    #
    # Every time a CorporateCard entity is updated, a corresponding CorporateCard::Log is generated for the entity. This log
    # is never generated by the user, but it can be retrieved to check additional information on the CorporateCard.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - card [CorporateCard]: CorporateCard entity to which the log refers to.
    # - type [string]: type of the CorporateCard event which triggered the log creation. ex: "blocked", "canceled", "created", "expired", "unblocked", "updated"
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :type, :card
      def initialize(id:, created:, type:, card:)
        super(id)
        @type = type
        @card = card
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific CorporateCard::Log
      #
      # Receive a single CorporateCard::Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - CorporateCard::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve CorporateCard::Logs
      #
      # Receive a generator of CorporateCard::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['blocked', 'canceled', 'created', 'expired', 'unblocked', 'updated']
      # - card_ids [list of strings, default nil]: list of CorporateCard ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: list of ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - generator of CorporateCard::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, card_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          card_ids: card_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged CorporateCard::Logs
      #
      # Receive a list of up to 100 CorporateCard::Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your logs.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['blocked', 'canceled', 'created', 'expired', 'unblocked', 'updated']
      # - card_ids [list of strings, default nil]: list of CorporateCard ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: list of ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - list of CorporateCard::Log objects with updated attributes
      # - Cursor to retrieve the next page of Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, card_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          card_ids: card_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkBank::CorporateCard.resource[:resource_maker]
        {
          resource_name: 'CorporateCardLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              created: json['created'],
              type: json['type'],
              card: StarkCore::Utils::API.from_api_json(request_maker, json['card'])
            )
          }
        }
      end
    end
  end
end
