# frozen_string_literal: true

require('starkcore')
require_relative('corporateholder')
require_relative('../utils/rest')

module StarkBank
  class CorporateHolder
    # # CorporateHolder::Log object
    #
    # Every time a CorporateHolder entity is updated, a corresponding CorporateHolder::Log is generated for the entity. This
    # log is never generated by the user, but it can be retrieved to check additional information on the CorporateHolder.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - holder [CorporateHolder]: CorporateHolder entity to which the log refers to.
    # - type [string]: type of the CorporateHolder event which triggered the log creation. ex: 'blocked', 'canceled', 'created', 'unblocked', 'updated'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :type, :holder
      def initialize(id:, created:, type:, holder:)
        super(id)
        @type = type
        @holder = holder
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific CorporateHolder::Log
      #
      # Receive a single CorporateHolder::Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - CorporateHolder::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve CorporateHolder::Logs
      #
      # Receive a generator of CorporateHolder::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'blocked']
      # - holder_ids [list of strings, default nil]: list of CorporateHolder ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: list of ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - generator of CorporateHolder::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, holder_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          holder_ids: holder_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged CorporateHolder::Logs
      #
      # Receive a list of up to 100 CorporateHolder::Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your holders.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'blocked']
      # - holder_ids [list of strings, default nil]: list of CorporateHolder ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: list of ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - list of CorporateHolder::Log objects with updated attributes
      # - cursor to retrieve the next page of Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, holder_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          holder_ids: holder_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkBank::CorporateHolder.resource[:resource_maker]
        {
          resource_name: 'CorporateHolderLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              created: json['created'],
              type: json['type'],
              holder: StarkCore::Utils::API.from_api_json(request_maker, json['holder'])
            )
          }
        }
      end
    end
  end
end
