# frozen_string_literal: true

require('starkcore')
require_relative('merchant_purchase')
require_relative('../utils/rest')

module StarkBank
  class MerchantPurchase
    # # MerchantPurchase::Log object
    #
    # Every time a MerchantPurchase entity is updated, a corresponding MerchantPurchase::Log is generated for the entity. This
    # log is never generated by the user.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - purchase [MerchantPurchase]: MerchantPurchase entity to which the log refers to.
    # - errors [list of hashes]: list of errors linked to this MerchantPurchase event, each with 'code' and 'message' keys
    # - type [string]: type of the MerchantPurchase event which triggered the log creation. ex: 'created', 'updated'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :type, :errors, :purchase
      def initialize(id:, created:, type:, errors:, purchase:)
        super(id)
        @type = type
        @errors = errors
        @purchase = purchase
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific MerchantPurchase::Log
      #
      # Receive a single MerchantPurchase::Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - MerchantPurchase::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve MerchantPurchase::Logs
      #
      # Receive a generator of MerchantPurchase::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by event types. ex: ['created', 'updated']
      # - purchase_ids [list of strings, default nil]: list of MerchantPurchase ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - generator of MerchantPurchase::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, purchase_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          purchase_ids: purchase_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged MerchantPurchase::Logs
      #
      # Receive a list of up to 100 MerchantPurchase::Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your logs.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by event types. ex: ['created', 'updated']
      # - purchase_ids [list of strings, default nil]: list of MerchantPurchase ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - list of MerchantPurchase::Log objects with updated attributes
      # - cursor to retrieve the next page of MerchantPurchase::Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, purchase_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          purchase_ids: purchase_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkBank::MerchantPurchase.resource[:resource_maker]
        {
          resource_name: 'MerchantPurchaseLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              created: json['created'],
              type: json['type'],
              errors: json['errors'],
              purchase: StarkCore::Utils::API.from_api_json(request_maker, json['purchase'])
            )
          }
        }
      end
    end
  end
end
