# frozen_string_literal: true

require('starkcore')
require_relative('merchant_installment')
require_relative('../utils/rest')

module StarkBank
  class MerchantInstallment
    # # MerchantInstallment::Log object
    #
    # Every time a MerchantInstallment entity is updated, a corresponding MerchantInstallment::Log is generated for the entity. This
    # log is never generated by the user.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - installment [MerchantInstallment]: MerchantInstallment entity to which the log refers to.
    # - errors [list of hashes]: list of errors linked to this MerchantInstallment event, each with 'code' and 'message' keys
    # - type [string]: type of the MerchantInstallment event which triggered the log creation. ex: 'created', 'updated'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    # - updated [DateTime]: latest update datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :updated, :type, :errors, :installment
      def initialize(id:, created:, updated:, type:, errors:, installment:)
        super(id)
        @type = type
        @errors = errors
        @installment = installment
        @created = StarkCore::Utils::Checks.check_datetime(created)
        @updated = StarkCore::Utils::Checks.check_datetime(updated)
      end

      # # Retrieve a specific MerchantInstallment::Log
      #
      # Receive a single MerchantInstallment::Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - MerchantInstallment::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve MerchantInstallment::Logs
      #
      # Receive a generator of MerchantInstallment::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by event types. ex: ['created', 'updated']
      # - installment_ids [list of strings, default nil]: list of MerchantInstallment ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - generator of MerchantInstallment::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, installment_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          installment_ids: installment_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged MerchantInstallment::Logs
      #
      # Receive a list of up to 100 MerchantInstallment::Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your logs.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by event types. ex: ['created', 'updated']
      # - installment_ids [list of strings, default nil]: list of MerchantInstallment ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
      #
      # ## Return:
      # - list of MerchantInstallment::Log objects with updated attributes
      # - cursor to retrieve the next page of MerchantInstallment::Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, installment_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          installment_ids: installment_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkBank::MerchantInstallment.resource[:resource_maker]
        {
          resource_name: 'MerchantInstallmentLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              created: json['created'],
              updated: json['updated'],
              type: json['type'],
              errors: json['errors'],
              installment: StarkCore::Utils::API.from_api_json(request_maker, json['installment'])
            )
          }
        }
      end
    end
  end
end
