# frozen_string_literal: true

require('starkcore')
require_relative('invoicepullrequest')
require_relative('../utils/rest')

module StarkBank
  class InvoicePullRequest
    # # InvoicePullRequest::Log object
    #
    # Every time an InvoicePullRequest entity is updated, a corresponding InvoicePullRequest::Log is generated for
    # the entity. This Log is never generated by the user, but it can be retrieved to check additional information
    # on the InvoicePullRequest.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - request [InvoicePullRequest]: InvoicePullRequest entity to which the log refers to.
    # - errors [list of strings]: list of errors linked to this InvoicePullRequest event
    # - type [string]: type of the InvoicePullRequest event which triggered the log creation. ex: 'pending' or 'success'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :request, :errors, :type, :created
      def initialize(id: nil, request: nil, errors: nil, type: nil, created: nil)
        super(id)
        @request = request
        @errors = errors
        @type = type
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific InvoicePullRequest::Log
      #
      # Receive a single InvoicePullRequest::Log object previously created by the Stark Bank API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - InvoicePullRequest::Log object with updated attributes
      def self.get(id, user: nil)
        StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve InvoicePullRequest::Logs
      #
      # Receive a generator of InvoicePullRequest::Log objects previously created in the Stark Bank API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'paid', 'canceled', 'overdue']
      # - request_ids [list of strings, default nil]: list of InvoicePullRequest ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - generator of InvoicePullRequest::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, request_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          request_ids: request_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged InvoicePullRequest::Logs
      #
      # Receive a list of up to 100 InvoicePullRequest::Log objects previously created in the Stark Bank API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your requests.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'paid', 'canceled', 'overdue']
      # - request_ids [list of strings, default nil]: list of InvoicePullRequest ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
      #
      # ## Return:
      # - list of InvoicePullRequest::Log objects with updated attributes and cursor to retrieve the next page of InvoicePullRequest::Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, request_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkBank::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          request_ids: request_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkBank::InvoicePullRequest.resource[:resource_maker]
        {
          resource_name: 'InvoicePullRequestLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              request: StarkCore::Utils::API.from_api_json(request_maker, json['request']),
              errors: json['errors'],
              type: json['type'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
