# frozen_string_literal: true

require('starkcore')
require_relative('../utils/rest')

module StarkBank
  # # Split object
  #
  # When you initialize a Split, the entity will not be automatically
  # created in the Stark Bank API. Splits are generated by the API when an
  # Invoice with split rules is paid, so this resource is used only to
  # retrieve Splits previously created that way.
  #
  # ## Parameters (required):
  # - amount [integer]: value to send to receivers. ex: 1000 (= R$ 10.00)
  # - receiver_id [string]: split receiver unique id. ex: '5656565656565656'
  #
  # ## Attributes (return-only):
  # - id [string]: unique id returned when split is created. ex: '5656565656565656'
  # - source [string]: source receivable which generated this split object. ex: '5656565656565656'
  # - external_id [string]: unique id, generated by the system, to avoid duplicated splits. ex: 'invoice/1234/receiver/5678'
  # - tags [list of strings, default nil]: list of strings for tagging
  # - scheduled [DateTime]: payment scheduled date or datetime. ex: DateTime.new(2020, 3, 10, 15, 17, 3)
  # - status [string]: current payment status. ex: 'success' or 'failed'
  # - created [DateTime]: creation datetime for the payment. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
  # - updated [DateTime]: update datetime for the payment. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
  class Split < StarkCore::Utils::Resource
    attr_reader :amount, :receiver_id, :id, :source, :external_id, :tags, :scheduled, :status, :created, :updated
    def initialize(
      amount:, receiver_id:, id: nil, source: nil, external_id: nil, tags: nil, scheduled: nil, status: nil,
      created: nil, updated: nil
    )
      super(id)
      @amount = amount
      @receiver_id = receiver_id
      @source = source
      @external_id = external_id
      @tags = tags
      @scheduled = StarkCore::Utils::Checks.check_datetime(scheduled)
      @status = status
      @created = StarkCore::Utils::Checks.check_datetime(created)
      @updated = StarkCore::Utils::Checks.check_datetime(updated)
    end

    # # Retrieve a specific Split
    #
    # Receive a single Split object previously created by the Stark Bank API by its id
    #
    # ## Parameters (required):
    # - id [string]: object unique id. ex: '5656565656565656'
    #
    # ## Parameters (optional):
    # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
    #
    # ## Return:
    # - Split object with updated attributes
    def self.get(id, user: nil)
      StarkBank::Utils::Rest.get_id(id: id, user: user, **resource)
    end

    # # Retrieve Splits
    #
    # Receive a generator of Split objects previously created in the Stark Bank API
    #
    # ## Parameters (optional):
    # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
    # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
    # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
    # - tags [list of strings, default nil]: tags to filter retrieved objects. ex: ['tony', 'stark']
    # - ids [list of strings, default nil]: list of ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
    # - receiver_ids [list of strings, default nil]: list of receiver ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
    # - status [string, default nil]: filter for status of retrieved objects. ex: 'success'
    # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
    #
    # ## Return:
    # - generator of Split objects with updated attributes
    def self.query(limit: nil, after: nil, before: nil, tags: nil, ids: nil, receiver_ids: nil, status: nil, user: nil)
      after = StarkCore::Utils::Checks.check_date(after)
      before = StarkCore::Utils::Checks.check_date(before)
      StarkBank::Utils::Rest.get_stream(
        limit: limit,
        after: after,
        before: before,
        tags: tags,
        ids: ids,
        receiver_ids: receiver_ids,
        status: status,
        user: user,
        **resource
      )
    end

    # # Retrieve paged Splits
    #
    # Receive a list of up to 100 Split objects previously created in the Stark Bank API and the cursor to the next page.
    # Use this function instead of query if you want to manually page your requests.
    #
    # ## Parameters (optional):
    # - cursor [string, default nil]: cursor returned on the previous page function call
    # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 50
    # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
    # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
    # - tags [list of strings, default nil]: tags to filter retrieved objects. ex: ['tony', 'stark']
    # - ids [list of strings, default nil]: list of ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
    # - receiver_ids [list of strings, default nil]: list of receiver ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
    # - status [string, default nil]: filter for status of retrieved objects. ex: 'success'
    # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkBank.user was set before function call
    #
    # ## Return:
    # - list of Split objects with updated attributes
    # - cursor to retrieve the next page of Split objects
    def self.page(
      cursor: nil, limit: nil, after: nil, before: nil, tags: nil, ids: nil, receiver_ids: nil, status: nil,
      user: nil
    )
      after = StarkCore::Utils::Checks.check_date(after)
      before = StarkCore::Utils::Checks.check_date(before)
      StarkBank::Utils::Rest.get_page(
        cursor: cursor,
        limit: limit,
        after: after,
        before: before,
        tags: tags,
        ids: ids,
        receiver_ids: receiver_ids,
        status: status,
        user: user,
        **resource
      )
    end

    def self.resource
      {
        resource_name: 'Split',
        resource_maker: proc { |json|
          Split.new(
            id: json['id'],
            amount: json['amount'],
            receiver_id: json['receiver_id'],
            source: json['source'],
            external_id: json['external_id'],
            tags: json['tags'],
            scheduled: json['scheduled'],
            status: json['status'],
            created: json['created'],
            updated: json['updated']
          )
        }
      }
    end
  end
end
